version: '3.8'

services:
  frontend:
    image: litheeshkumar/gxp-frontend:v1
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${"http://host.docker.internal:8000"}
    depends_on:
      - backend

  backend:
    image: litheeshkumar/gxp-backend:v1
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - MODEL_API_URL=${"http://host.docker.internal:5000"}
    depends_on:
      - model

  model:
    image: litheeshkumar/verixa_model_devops:latest
    ports:
      - "${MODEL_PORT}:5000"
